---
# IT IS RECOMMENDED YOU DO NOT CHANGE THE IMAGES TO BE DOWNLOADED.
kubeversion: "v1.20"

images:
  # "images.attacher" defines the container images used for the csi attacher
  # container.
  attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.2.1

  # "images.provisioner" defines the container images used for the csi provisioner
  # container.
  provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v2.2.1

  # "images.snapshotter" defines the container image used for the csi external snapshotter
  snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v4.1.0

  # "images.registrar" defines the container images used for the csi registrar
  # container.
  registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.2.0

  # "images.resizer" defines the container images used for the csi resizer
  # container.
  resizer: k8s.gcr.io/sig-storage/csi-resizer:v1.2.0

  # "images.healthmonitor" defines the container images used for the csi external health monitor
  # container.
  healthmonitor: k8s.gcr.io/sig-storage/csi-external-health-monitor-controller:v0.4.0
