  # Username for accessing PowerFlex system.
  # If authorization is enabled, username will be ignored.
- username: "admin"
  # Password for accessing PowerFlex system.
  # If authorization is enabled, password will be ignored.
  password: "password"
  # System name/ID of PowerFlex system.	
  systemID: "ID1"
  # Previous names used in secret of PowerFlex system.
  allSystemNames: "pflex-1,pflex-2"
  # REST API gateway HTTPS endpoint for PowerFlex system.
  # If authorization is enabled, endpoint should be the HTTPS localhost endpoint that 
  # the authorization sidecar will listen on
  endpoint: "https://127.0.0.1"
  # Determines if the driver is going to validate certs while connecting to PowerFlex REST API interface.
  # Allowed values: true or false
  # Default value: true
  skipCertificateValidation: true 
  # indicates if this array is the default array
  # needed for backwards compatibility
  # only one array is allowed to have this set to true 
  # Default value: false
  isDefault: true
  # defines the MDM(s) that SDC should register with on start.
  # Allowed values:  a list of IP addresses or hostnames separated by comma.
  # Default value: none 
  
  # NFS is only supported on arrays >= 4.0
  # nasName: what NAS should be used for NFS volumes
  # Allowed Values: string - (name of NAS server)
  # Default Value: None
  nasName: "nas-server"

  # nfsAcls: enables setting permissions on NFS mount directory
  # This value will be used if a storage class does not have the NFS ACL (nfsAcls) parameter specified
  # Permissions can be specified in two formats:
  #   1) Unix mode (NFSv3)
  #   2) NFSv4 ACLs (NFSv4)
  #      NFSv4 ACLs are supported on NFSv4 share only.
  # Allowed values:
  #   1) Unix mode: valid octal mode number
  #      Examples: "0777", "777", "0755"
  #   2) NFSv4 acls: valid NFSv4 acls, seperated by comma
  #      Examples: "A::OWNER@:RWX,A::GROUP@:RWX", "A::OWNER@:rxtncy"
  # Optional: true
  # Default value: "0777"
  # nfsAcls: "0777"  

  mdm: "10.0.0.1,10.0.0.2"
- username: "admin"
  password: "Password123"
  systemID: "ID2"
  endpoint: "https://127.0.0.2"
  skipCertificateValidation: true 
  mdm: "10.0.0.3,10.0.0.4"
