# Copyright (c) 2024 Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0

# Reusable workflow to perform image version update on Golang based projects
name: Image Version Update

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  repository_dispatch:
    types: [image-update-workflow]

jobs:
  # image version update
  image-version-update:
    uses: dell/common-github-actions/.github/workflows/image-version-workflow.yaml@main
    with:
      version: "minor"
    secrets: inherit
